### ISSUE TITLE
Add Keyboard shortcuts

### ISSUE THREAD

**Issue by maymage** [FineFindus/Hieroglyphic#5]
Hi, 

I just tested the app - it is functional and just nice!

Yet trackpad+keyboard usability could be slightly improved, e.g. via

* `Esc` and/or `Del` and/or `Backspace`  clearing, what was drawn
* `Arrow+{Up,Down}` scrolling through the match list and of course 
* hitting enter saves the selected latex command to the clipboard

The rational is, that drawing in case of a trackpad+keyboard only situation, of course one has to draw with the trackpad, but clearing, scrolling the match list and selecting is faster via keyboard.

**Comment by FineFindus** [comment]
Thanks for quite the early feedback!

> Esc and/or Del and/or Backspace clearing, what was drawn

Planned feature, though I'm not quite sure which key to use. It'll be in the next release.

> Arrow+{Up,Down} scrolling through the match list and of course

This can already be done using the available focus system that GTK provides. Additionally, since the correct result is usually at/near the top, I don't think there is any value in providing a redundant way of scrolling the list.

> hitting enter saves the selected latex command to the clipboard

That is already the case when the command is focused?
